import type { Category, Product } from '@/types'

export const previewCategories: Category[] = [
  { id: 'preview-food', name: 'مواد غذائية', slug: 'food', parent_id: null, icon: null, sort_order: 1, is_active: true, created_at: '2026-01-01' },
  { id: 'preview-packaging', name: 'مستلزمات التغليف', slug: 'packaging', parent_id: null, icon: null, sort_order: 2, is_active: true, created_at: '2026-01-01' },
  { id: 'preview-cleaning', name: 'مواد التنظيف', slug: 'cleaning', parent_id: null, icon: null, sort_order: 3, is_active: true, created_at: '2026-01-01' },
]

export const previewProducts: Product[] = [
  { id: 'preview-rice', sku: 'DEMO-001', name: 'Premium Rice', name_ar: 'أرز بسمتي فاخر', slug: 'premium-rice', description: 'بيانات عرض توضيحية للكتالوج فقط.', category_id: 'preview-food', brand_id: null, unit: 'كرتون', box_quantity: 10, carton_quantity: 40, min_order_qty: 1, price: 125, bulk_price: 112, cost_price: 0, base_price: 125, retail_price: 125, wholesale_price: 112, stock_quantity: 100, reserved_stock: 0, weight: 20, barcode: null, image_url: null, is_active: true, is_featured: true, is_new: true, tags: ['معاينة'], created_at: '2026-01-01', updated_at: '2026-01-01', category: previewCategories[0] },
  { id: 'preview-oil', sku: 'DEMO-002', name: 'Sunflower Oil', name_ar: 'زيت دوار الشمس', slug: 'sunflower-oil', description: 'بيانات عرض توضيحية للكتالوج فقط.', category_id: 'preview-food', brand_id: null, unit: 'كرتون', box_quantity: 12, carton_quantity: 48, min_order_qty: 1, price: 98, bulk_price: 88, cost_price: 0, base_price: 98, retail_price: 98, wholesale_price: 88, stock_quantity: 65, reserved_stock: 0, weight: 12, barcode: null, image_url: null, is_active: true, is_featured: true, is_new: false, tags: ['معاينة'], created_at: '2026-01-01', updated_at: '2026-01-01', category: previewCategories[0] },
  { id: 'preview-box', sku: 'DEMO-003', name: 'Shipping Boxes', name_ar: 'كراتين شحن متعددة المقاسات', slug: 'shipping-boxes', description: 'بيانات عرض توضيحية للكتالوج فقط.', category_id: 'preview-packaging', brand_id: null, unit: 'حزمة', box_quantity: 25, carton_quantity: 100, min_order_qty: 1, price: 45, bulk_price: 39, cost_price: 0, base_price: 45, retail_price: 45, wholesale_price: 39, stock_quantity: 240, reserved_stock: 0, weight: 4, barcode: null, image_url: null, is_active: true, is_featured: true, is_new: true, tags: ['معاينة'], created_at: '2026-01-01', updated_at: '2026-01-01', category: previewCategories[1] },
  { id: 'preview-cleaner', sku: 'DEMO-004', name: 'Surface Cleaner', name_ar: 'منظف أسطح احترافي', slug: 'surface-cleaner', description: 'بيانات عرض توضيحية للكتالوج فقط.', category_id: 'preview-cleaning', brand_id: null, unit: 'كرتون', box_quantity: 6, carton_quantity: 24, min_order_qty: 1, price: 72, bulk_price: 64, cost_price: 0, base_price: 72, retail_price: 72, wholesale_price: 64, stock_quantity: 42, reserved_stock: 0, weight: 8, barcode: null, image_url: null, is_active: true, is_featured: false, is_new: true, tags: ['معاينة'], created_at: '2026-01-01', updated_at: '2026-01-01', category: previewCategories[2] },
]
